spring:
  application:
    name: testTask

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testTask
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

jwt:
  secret: testsecretsecretsecretsecretsecretsecretsecret
balance:
  cron: "0/15 * * * * ?"


